### ISSUE TITLE
toggle 제어

### ISSUE THREAD

**Issue by sihyeokpark** [1-EXON/DarkAlgo#2]
https://github.com/1-EXON/DarkAlgo/blob/master/extension/index.html
switch 를 js 로 어떻게 키고 끌 수 있을까요?

**Comment by sihyeokpark** [comment]
![image](https://user-images.githubusercontent.com/56220973/91383325-d40ab080-e866-11ea-9fd8-4ca0a8d0fbc4.png)

**Comment by pmh-only** [comment]
간단

**Comment by pmh-only** [comment]
document.getElementById('DarkBtn').checked = true

**Comment by pmh-only** [comment]
아니면 `<input id="DarkBtn" type="checkbox" checked>`해도 됨

**Comment by sihyeokpark** [comment]
감사합니다!
